name: .NET Core
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
env:
  NUGET_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  GitHubPackageFeedUrl: 'https://nuget.pkg.github.com/AzureSprint-20201202-tiger/index.json'
  LogicProjectPath: '${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic'
  AzureWebAppName: webapptesteric
  AzureWebAppPackagePath: '.'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          source-url: '${{ env.GitHubPackageFeedUrl }}'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: >-
          dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore
          --verbosity normal
      - name: Create Artifact
        run: >-
          dotnet publish AnimalAdoption.Web.Portal -o
          AnimalAdoption.Web.Portal/published
      - name: Search Artifact
        run: 'ls -al ${{ github.workspace }}/AnimalAdoption.Web.Portal/published'
      - uses: actions/upload-artifact@v2
        with:
          name: Web Portal Artifact
          path: '${{ github.workspace }}/AnimalAdoption.Web.Portal/published'
      - name: Package up project
        run: 'dotnet pack --configuration Release ${{ env.LogicProjectPath }}'
      - name: check pack
        run: 'ls -al ${{ env.LogicProjectPath }}'
      - name: Push package to GitHub registry
        run: >-
          dotnet nuget push ${{ env.LogicProjectPath }}/**/*.nupkg
          --skip-duplicate
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Web Portal Artifact
      - name: Display structure of downloaded files
        run: ls -R
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.PUBLISH_CREDENTIALS_TEST }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          app_location: '/' # App source code path
          api_location: 'api' # Api source code path - optional
          app_artifact_location: 'dist' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
