name: .NET Core

on:
  push:
    branches: #[ master ] 
      - '**'
  pull_request:
    branches: #[ master ]
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create Artifact
      run: dotnet publish AnimalAdoption.Web.Portal -o AnimalAdoption.Web.Portal/published
    - name: Search Artifact
      run: ls -al ${{ github.workspace }}/AnimalAdoption.Web.Portal/published


